"""remove user_mail from log

Revision ID: b47f232393ad
Revises: 97275903c3de
Create Date: 2026-01-20 20:51:40.485554

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b47f232393ad"
down_revision = "97275903c3de"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("door_access_log", schema=None) as batch_op:
        batch_op.drop_column("user_email")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("door_access_log", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_email", sa.VARCHAR(length=255), nullable=False))

    # ### end Alembic commands ###
